# App
spring.application.name=backend
server.port=8080

# Neo4j
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=your_password

# FusionAuth JWT
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9011

# TMDB
tmdb.api.key=eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI0MmU4YmMyYjRkZjgwZDY2NDYyYjM2MjU1MzE0MWU1MiIsIm5iZiI6MTc3ODk3OTA4MC42NjYsInN1YiI6IjZhMDkxMTA4ZmUyMmMwN2ZiMDdhOGM0YyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.mHG9fpj7__YNBUkflalGOZH4sHqr2WWsvktjdBpCOZ8
tmdb.base.url=https://api.themoviedb.org/3